require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer

Metrics/ParameterLists:
  Exclude: 
    - 'app/models/car.rb'

Metrics/AbcSize:
  Max: 25
