require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude: 
    - 'lib/models/car/car_storer.rb'
    - 'lib/models/car/car.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

Metrics/ParameterLists:
  Exclude: 
    - 'lib/models/car/car.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/models/transforming_values.rb'
    - 'lib/models/search/filter_cars.rb'
    - 'lib/models/console_prettier.rb'
    - 'lib/views/cars_table.rb'
